name: Cameron
favicon: null
layout_spectrum: 0.23632
typography_spectrum: 0.78753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b77539'
    - '#414b1b'
    - '#e0b690'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
